### ISSUE TITLE
[feat] QuestionResultView 항목 함수 구현

### ISSUE THREAD

**Issue by greetings1012** [SJU-CapstoneDesign/D3N-iOS#16]
## 👀 Issue
QuestionResultView 안의 문제 및 정답 표시 항목들을 함수로 나누어 외부에 선언

### ✅ Todo
- [ ] 문제를 보여주는 함수
- [ ] 보기를 보여주는 함수
- [ ] 해설을 보여주는 함수
